### ISSUE TITLE
Application on assembled genomes

### ISSUE THREAD

**Issue by sivico26** [noraracht/CONSULT#5]
Hi!, thanks for developing Consult.

I was wondering if Consult can be somewhat repurposed to be used not in raw reads but assembled contigs/scaffolds. I already have an assembly assembled from unfiltered reads but it does have contamination (at least some organellar contigs). I want to identify and filter them out. I do have the chloroplast that contaminates the assembly. I was thinking of using it as the database of kmers and then query the assembly against it.

What do you think? Do you think it would work? What considerations should I bear in mind? When I have tried other methods, I have observed that some contigs are clearly parts of the organelle (alignments > 90% of length); Most, on the other hand, present good alignments but rather short, with a big proportion of unaligned sequence, which makes me hesitate.

Anyway, I would love to know your thoughts.

**Comment by noraracht** [comment]
Hi Simon,

We are glad to hear that consult might be useful for your work.

All our assumptions for kmer matching are centered around raw reads. If
applied to contigs in a current state tool will most likely be
overfiltering contigs.
However for your workflow we would suggest the following. You should be
able to generate error free shorter simulated reads from your assemblies.
For instance, you can use ART and do it with the script. Then filter reads
against the chloroplast database and reassemble clean nuclear reads. Also
since identity to chloroplast genomes is pretty high we would suggest to
use higher value for c (number of k-mers to call read classified). This
will allow to keep false positives under control and limit overfiltering of
nuclear sequences..

Thank you,
Nora

**Comment by sivico26** [comment]
Interesting approach, I might give it a try and let you know how it works out if it is of interest. Anyway, I will close the issue for now. 

Thank you for your thoughts.
Regards.

**Comment by noraracht** [comment]
Hi Simon,

Certainly if you happen to test suggested workflow please let us know
whether it worked for you or not.

Thank you for reaching out,
Nora
